version: '2'
services:

    # https://hub.docker.com/r/jetbrains/teamcity-server/
    server:
        build: ./docker/teamcity-server
        volumes:
            - "./data/teamcity-server/data:/data/teamcity_server/datadir"
            - "./data/teamcity-server/logs:/opt/teamcity/logs"
        ports:
            - "8111:8111"
        environment:
            TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
            TEAMCITY_DATABASE_HOST: db
        links: [ "db" ]

    # https://hub.docker.com/_/mariadb/
    db:
        image: mariadb:latest
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: teamcity
            MYSQL_USER: teamcity
            MYSQL_PASSWORD: teamcity

    agent:
        build: ./docker/teamcity-agent
        depends_on: ["server"]
        environment:
            SERVER_URL: "http://server:8111"
        links: [ "server" ]
